language: julia
sudo: false
os:
    - linux
addons:
  apt:
    packages:
    - libnlopt0
    - hdf5-tools
julia:
    - 0.7
matrix:
    allow_failures:
notifications:
    email: false
#script: # use the default script setting which is equivalent to the following
after_success:
    - echo $TRAVIS_JULIA_VERSION
    - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("QuantEcon")); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
    - julia -e 'Pkg.add("Documenter")'
    - julia -e 'cd(Pkg.dir("QuantEcon")); include(joinpath("docs", "make.jl"))'
